# Generated by Django 4.0.3 on 2022-03-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=15)),
                ('major', models.CharField(choices=[('IT', 'Information Technologies'), ('MIS', 'Management Information Systems'), ('MRK', 'Marketing'), ('ECO', 'Economics')], max_length=3)),
                ('ci', models.DecimalField(decimal_places=2, max_digits=5)),
                ('registration_date', models.DateTimeField()),
                ('total_credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('course_code', models.CharField(max_length=15, unique=True)),
                ('course_credits', models.ManyToManyField(blank=True, to='courses.student')),
            ],
        ),
    ]
