# Generated by Django 4.0.3 on 2022-03-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_credits',
        ),
        migrations.AddField(
            model_name='course',
            name='course_credits',
            field=models.IntegerField(default=0),
        ),
    ]
